services:
  - type: web
    name: webauthn-biometrics
    env: node
    plan: free
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGODB_URI
        sync: false
